debug: true
insults:
  - "You're a cockalorum"
  - "Someday you'll go far, and I hope that you will stay there"
  - "I love what you have done with your hair! How did you get it come out of your nostrils like that?"
  - "You're the reason that God created the middle finger"
  - "You're the gray sprinkle on the rainbow cupcake"
  - "You bring everyone so much joy when you leave the room!"