#                                                                           #
#|------------------------------------------------------------------------| #
#|        MINECRAFT MANHUNT, BUT THE HUNTER HAS SPECIAL ABILITIES         | #
#|                             v1.0 RELEASE                               | #
#|                                                                        | #
#|                        BY: EMERALDWITHERYT                             | #
#|------------------------------------------------------------------------| #
#                                                                           #
plugin-prefix: "&2[Abilities Manhunt] "
config-reload-msg: "&aSuccessfully reloaded the configuration files!"
messages:
  # Placeholders
  # %time-left% : Gets the remaining time left on cooldown! Does NOT work with the mana-error-msg.
  cooldown-msg: "&4[Error] &cYou're currently on cooldown for the \"&4&l%ability%&c\" ability! You still have &4&l%time-left% &cseconds remaining!"
  mana-error-msg: "&4[Error] &cYou do not have enough mana for that!"
  start-msg:
    - "&c-----------------"
    - "&aThe manhunt is starting now!"
    - "&c----------------"
  force-end-msg:
    # Force-end Placeholders
    # %player% : Gets the player who force-ended the game!
    - "&6---------------------------------"
    - "&4The game has been forcibly ended by &4&l%player%&4."
    - "&6---------------------------------"
  hunter-win-msg:
    hunters:
      - "&6-------------------------------"
      - "&aYou have won the game!"
      - "&6-------------------------------"
    speedrunners:
      - "&6-------------------------------"
      - "&4You have lost the game :("
      - "&6-------------------------------"
  speedrunner-win-msg:
    hunters:
      - "&6-------------------------------"
      - "&4You have lost the game :("
      - "&6-------------------------------"
    speedrunners:
      - "&6--------------------------------"
      - "&aYou have won the game!"
      - "&6--------------------------------"

  # Global Placeholders For "Abilities"
  # %hunter% : Gets the name of the hunter who is trying to use the ability.
  # %speedrunner% : Gets the name of the selected speedrunner.
  #
  # The above placeholders can be used anywhere in the abilities section for "msg" parameter.
  #
  # The "msg" parameter is the message that is sent to the hunter when the ability is used.
  # Some abilities may also have their own special placeholders outlined below.
  #
  # ALL cooldowns should be in SECONDS!

abilities:
  lightning:
    cooldown: 30
    msg: "&aYou have struck lightning down on &2%speedrunner%&a!"
    speedrunner-msg: "&cYou have been stuck down with lightning by &4%hunter%&c!"
  launcher:
    # Launcher Placeholders
    # %velocity% : Gets the launch velocity specified here
    #                |
    #                V
    launch-velocity: 10
    launch-upwards: false
    # If launch-upwards is false, the
    # speedrunner will be launched in
    # the direction that they are looking at.
    cooldown: 30
    msg: "&aLaunched &2%speedrunner% &ainto the air with a velocity of &2%velocity%&a!"
    speedrunner-msg: "&cYou have been launched into the air by &4%hunter%&c, with a velocity of &4%velocity%&c!"
  gravity:
    # Launcher Placeholders
    # %radius% : Gets the radius of which the gravity ability applies.
    #       |
    #       V
    radius: 5
    cooldown: 60
    msg: "&aApplied gravity to all blocks around &2%speedrunner%&a in a &2%radius% &ablock radius!"
    speedrunner-msg: "&4%hunter% &chas applied gravity to all blocks around you in a &4%radius% &cblock radius!"
  randomtp:
    # RandomTP Placeholders
    # %distance% : Gets the distance traveled by the RandomTP.
    tp-radius: 50
    cooldown : 100
    msg: "&aRandomly teleported &2%hunter% &ato a distance &2%distance% &ablock(s) away!"
    speedrunner-msg: "&cYou have been randomly teleported &4%distance% &cblock(s) away by &4%hunter%&c!"
  damageitem:
    # DamageItem Placeholders
    # %items% : Gets the number of affected items in the speedrunners inventory.
    cooldown: 120
    msg: "&aDamaged &2%items% &aitem(s) in &2%speedrunner%&a's inventory!"
    speedrunner-msg: "&4%hunter% &chas damaged &4%items% &citem(s) in your inventory!"
  playertp:
    height-above-player: 5
    msg: "&aTeleported you to &2%speedrunner%&a!"
    speedrunner-msg: "&4%hunter% &chas teleported to you!"
  mob-targeting:
    # Scramble Placeholders
    # %mobs% : Gets the number of mobs that will target the speedrunner.
    range: 200
    cooldown: 600
    msg: "&aNow sending &2%mobs% &amob(s) to attack &2%speedrunner%&a!"
    speedrunner-msg: "&4%hunter% &chas commanded &4%mobs% &cmobs to attack you!"
  scramble:
    # Scramble Placeholders
    # %items% : Gets the number of affected items.
    cooldown: 100
    msg: "&aNow scrambling &2%items% &aitem(s) in &2%speedrunner%s &ainventory!"
    speedrunner-msg: "&4%hunter% &chas scrambled &4%items% &citem(s) in your inventory!"
  freeze:
    #Time is how long the speedrunner will be frozen for.
    time: 5
    cooldown: 80
    msg: "&aNow freezing &2%speedrunner% &afor &2%time% &aseconds!"
    unfreeze-msg: "&2%speedrunner% &ahas been unfrozen!"
    speedrunner-freeze-msg: "&cYou have been frozen by &4%hunter%&c for &4%time% &csecond(s), and cannot move!"
    speedrunner-unfreeze-msg: "&aYou have been unfrozen and move again!"
    prevent-kicking: true
    # This prevent the player for being kicked due to the the "Flying is not enabled on this server" kick message.
    # It is suggested that you do not change this

# This will remove any special items as
# to prevent them from being used.
# It is not suggested you change this!
clear-items-on-join: true
clear-items-on-leave: true
