main: org.emeraldcraft.manhunt.ManhuntMain
name: ManhuntAbilities
description: Minecraft Manhunt, but the Hunter has Special Abilities!
version: ${version}
api-version: 1.18
commands:
  manhunt:

  shop:

